### ISSUE TITLE
Jabref is outdated

### ISSUE THREAD

**Issue by ArnaudDvs** [OlafHaag/chocolatey-packages#28] opened 2023-10-25 15:42 UTC
The Chocolatey package is for Jabref 5.8, whereas the latest version of Jabref is 5.11. Could the package be updated?

**Comment by OlafHaag** [comment] 2023-11-19 00:55
Thanks for the hint! I'll take a look.

**Comment by OlafHaag** [comment] 2023-11-19 01:28
closing as duplicate of re-opened #6

**Closed as completed by OlafHaag** 2023-11-19 01:28 UTC
